In [10]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# load NN_dataset
filepath = "NN_dataset.csv"
NN_data = pd.read_csv(filepath)
NN_data.columns

Index(['Customer_ID', 'Num_CC', 'Dependents', 'Status_Checking_Acc',
       'Credit_History', 'Purposre_Credit_Taken', 'Savings_Acc',
       'Years_At_Present_Employment', 'Marital_Status_Gender',
       'Other_Debtors_Guarantors', 'Other_Inst_Plans ', 'Housing', 'Job',
       'Telephone', 'Foreign_Worker', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned', 'Default_On_Payment'],
      dtype='object')

In [11]:
# set Customer_ID as index
NN_data.set_index('Customer_ID',inplace=True)

In [12]:
NN_data.dtypes

Num_CC                          int64
Dependents                      int64
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [13]:
NN_data['Num_CC'] = NN_data['Num_CC'].astype(str)
NN_data['Dependents'] = NN_data['Dependents'].astype(str)

In [14]:
NN_data.dtypes

Num_CC                         object
Dependents                     object
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [15]:
NN_data = NN_data.drop(columns=['Num_CC', 'Dependents', 'Status_Checking_Acc', 'Credit_History', 'Savings_Acc', 'Marital_Status_Gender', 'Other_Inst_Plans ', 'Job',
       'Telephone', 'Foreign_Worker'])

In [16]:
NN_data.dtypes

Purposre_Credit_Taken          object
Years_At_Present_Employment    object
Other_Debtors_Guarantors       object
Housing                        object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [17]:
NN_data.columns

Index(['Purposre_Credit_Taken', 'Years_At_Present_Employment',
       'Other_Debtors_Guarantors', 'Housing', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned', 'Default_On_Payment'],
      dtype='object')

In [18]:
NN_data.head()

Purposre_Credit_Taken Years_At_Present_Employment  \
Customer_ID                                                     
100001                        A43                         A75   
100002                        A43                         A73   
100003                        A46                         A74   
100004                        A42                         A74   
100005                        A40                         A73   

            Other_Debtors_Guarantors Housing Duration_binned  \
Customer_ID                                                    
100001                          A101    A152             B10   
100002                          A101    A152             B14   
100003                          A101    A152             B11   
100004                          A103    A153             B13   
100005                          A101    A153             B12   

            Credit_amount_binned Age_binned  Default_On_Payment  
Customer_ID                                                      
100001                       B20        B35                   0  
100002                       B22        B30                   0  
100003                       B20        B33                   0  
100004                       B23        B33                   0  
100005                       B21        B33                   1

In [19]:
NN_data = pd.get_dummies(NN_data, prefix=['Purposre_Credit_Taken', 'Years_At_Present_Employment',
       'Other_Debtors_Guarantors', 'Housing', 'Duration_binned', 
       'Credit_amount_binned', 'Age_binned'])

In [20]:
NN_data

Default_On_Payment  Purposre_Credit_Taken_A40  \
Customer_ID                                                  
100001                        0                          0   
100002                        0                          0   
100003                        0                          0   
100004                        0                          0   
100005                        1                          1   
...                         ...                        ...   
104996                        0                          0   
104997                        0                          0   
104998                        0                          0   
104999                        1                          0   
105000                        0                          0   

             Purposre_Credit_Taken_A41  Purposre_Credit_Taken_A410  \
Customer_ID                                                          
100001                               0                           0   
100002                               0                           0   
100003                               0                           0   
100004                               0                           0   
100005                               0                           0   
...                                ...                         ...   
104996                               0                           0   
104997                               1                           0   
104998                               0                           0   
104999                               0                           0   
105000                               1                           0   

             Purposre_Credit_Taken_A42  Purposre_Credit_Taken_A43  \
Customer_ID                                                         
100001                               0                          1   
100002                               0                          1   
100003                               0                          0   
100004                               1                          0   
100005                               0                          0   
...                                ...                        ...   
104996                               1                          0   
104997                               0                          0   
104998                               0                          1   
104999                               0                          1   
105000                               0                          0   

             Purposre_Credit_Taken_A44  Purposre_Credit_Taken_A45  \
Customer_ID                                                         
100001                               0                          0   
100002                               0                          0   
100003                               0                          0   
100004                               0                          0   
100005                               0                          0   
...                                ...                        ...   
104996                               0                          0   
104997                               0                          0   
104998                               0                          0   
104999                               0                          0   
105000                               0                          0   

             Purposre_Credit_Taken_A46  Purposre_Credit_Taken_A48  ...  \
Customer_ID                                                        ...   
100001                               0                          0  ...   
100002                               0                          0  ...   
100003                               1                          0  ...   
100004                               0                          0  ...   
100005                               0                 

In [21]:
data = NN_data.values
X = data[:, 1:77]
y = data[:, 0]

In [22]:
X.shape, y.shape

((5000, 41), (5000,))

In [23]:
X[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [24]:
# one-hot encode y (y data is already label encoded)
one_hot_y = to_categorical(y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [25]:
one_hot_y[0]

array([1., 0.], dtype=float32)

In [26]:
#split data to train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, random_state=1)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3750, 41), (1250, 41), (3750, 2), (1250, 2))

In [28]:
# create basic single hidden layer model to test (ignore future version warning)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model_TEST = Sequential()
model_TEST.add(Dense(units=51, activation='relu', input_dim=41))
model_TEST.add(Dense(units=51, activation='relu'))
model_TEST.add(Dense(units=51, activation='relu'))
model_TEST.add(Dense(units=2, activation='softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [29]:
model_TEST.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 51)                2142      
_________________________________________________________________
dense_1 (Dense)              (None, 51)                2652      
_________________________________________________________________
dense_2 (Dense)              (None, 51)                2652      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 104       
Total params: 7,550
Trainable params: 7,550
Non-trainable params: 0
_________________________________________________________________


In [30]:
# Compile the model
model_TEST.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [31]:
# Fit the model to the training data
model_TEST.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
3750/3750 - 0s - loss: 0.5818 - acc: 0.6944
Epoch 2/100
3750/3750 - 0s - loss: 0.5055 - acc: 0.7525
Epoch 3/100
3750/3750 - 0s - loss: 0.4552 - acc: 0.7795
Epoch 4/100
3750/3750 - 0s - loss: 0.4028 - acc: 0.8139
Epoch 5/100
3750/3750 - 0s - loss: 0.3516 - acc: 0.8477
Epoch 6/100
3750/3750 - 0s - loss: 0.3123 - acc: 0.8707
Epoch 7/100
3750/3750 - 0s - loss: 0.2786 - acc: 0.8837
Epoch 8/100
3750/3750 - 0s - loss: 0.2500 - acc: 0.8971
Epoch 9/100
3750/3750 - 0s - loss: 0.2249 - acc: 0.9067
Epoch 10/100
3750/3750 - 0s - loss: 0.2146 - acc: 0.9128
Epoch 11/100
3750/3750 - 0s - loss: 0.2006 - acc: 0.9155
Epoch 12/100
3750/3750 - 0s - loss: 0.1922 - acc: 0.9197
Epoch 13/100
3750/3750 - 0s - loss: 0.1869 - acc: 0.9203
Epoch 14/100
3750/3750 - 0s - loss: 0.1831 - acc: 0.9176
Epoch 15/100
3750/3750 - 0s - loss: 0.1767 - acc: 0.9216
Epoch 16/100
3750/3750 - 0s - loss: 0.1756 - acc: 0.9224
Epo

In [32]:
model_loss, model_accuracy = model_TEST.evaluate(
    X_test, y_test, verbose=2)
print(f"model_TEST - Loss: {model_loss}, Accuracy: {model_accuracy}")

1250/1250 - 0s - loss: 0.1397 - acc: 0.9224
model_TEST - Loss: 0.13967388846874237, Accuracy: 0.9223999977111816


In [33]:
from sklearn.metrics import classification_report

predictions = model_TEST.predict(X_test).round()
print(classification_report(y_test, predictions, target_names=["no-default", "default"]))
                            

              precision    recall  f1-score   support

  no-default       0.93      0.96      0.95       901
     default       0.90      0.81      0.85       349

   micro avg       0.92      0.92      0.92      1250
   macro avg       0.91      0.89      0.90      1250
weighted avg       0.92      0.92      0.92      1250
 samples avg       0.92      0.92      0.92      1250



In [63]:
application_data = NN_data.loc[100001]
application_data.dtype

dtype('int64')

In [34]:
solo_test = np.expand_dims(X_test[0], axis=0)
prediction = model_TEST.predict(solo_test).round()
actual = y_test[0]

print(prediction, actual)

[[1. 0.]] [1. 0.]


Precision is the ability of a classifier not to label an instance positive that is actually negative. For each class it is defined as as the ratio of true positives to the sum of true and false positives. Said another way, “for all instances classified positive, what percent was correct?”

Recall is the ability of a classifier to find all positive instances. For each class it is defined as the ratio of true positives to the sum of true positives and false negatives. Said another way, “for all instances that were actually positive, what percent was classified correctly?”

The F1 score is a weighted harmonic mean of precision and recall such that the best score is 1.0 and the worst is 0.0. Generally speaking, F1 scores are lower than accuracy measures as they embed precision and recall into their computation. As a rule of thumb, the weighted average of F1 should be used to compare classifier models, not global accuracy.

Support is the number of actual occurrences of the class in the specified dataset. Imbalanced support in the training data may indicate structural weaknesses in the reported scores of the classifier and could indicate the need for stratified sampling or rebalancing. Support doesn’t change between models but instead diagnoses the evaluation process.